export const actors = [
    {
        id: 1,
        img: 'https://th.bing.com/th/id/R.8fd7bd32114fac8a033ef114b33e7f73?rik=sw6MqBhzBezvVQ&riu=http%3a%2f%2fimages2.fanpop.com%2fimages%2fphotos%2f5100000%2fDominic-3-dominic-purcell-5111149-1863-2560.jpg&ehk=Yq7EJm9JM%2bIrvDxR2d2sNJkh52KfWl2lL9%2fiAcc14Gs%3d&risl=&pid=ImgRaw&r=0',
        name: 'Dominic Purcell',
        role: 'Lincoln `Linc` Burrows',
        eps: '90',
    },
    {
        id: 2,
        img: 'https://th.bing.com/th/id/R.a202850500c6ccceafeb39ec28514c99?rik=X4sF64JtTfn7pQ&pid=ImgRaw&r=0',
        name: 'Wentworth Miller',
        role: 'Michael Scofield',
        eps: '90',
    },
    {
        id: 3,
        img: 'https://th.bing.com/th/id/R.f750ff82a707e742530c1eaab4cc64dc?rik=uKx3n82hQjeLpQ&pid=ImgRaw&r=0',
        name: 'Amaury Nolasco',
        role: 'Fernando Sucre',
        eps: '79',
    },
    {
        id: 4,
        img: 'https://th.bing.com/th/id/OIP._lTOsgtziaPyCwVYPTJK1wAAAA?pid=ImgDet&rs=1',
        name: 'Robert Knepper',
        role: 'Theodore `T-Bag` Bagwell',
        eps: '87',
    },
    {
        id: 5,
        img: 'https://th.bing.com/th/id/R.3bd073067fdb51383767a09b494648bc?rik=qRfdGNlF5txbwQ&pid=ImgRaw&r=0',
        name: 'Sarah Wayne Callies',
        role: 'Sara Tancredi',
        eps: '63',
    },
    {
        id: 6,
        img: 'https://th.bing.com/th/id/R.e05f6f4d76add89be2273e85139aa46b?rik=ew1N5Fzf91RcNw&pid=ImgRaw&r=0',
        name: 'Wade Williams',
        role: 'Brad Bellick',
        eps: '76',
    },
    {
        id: 7,
        img: 'https://th.bing.com/th/id/OIP.8iHcdzglDr8AVGiJirHnngAAAA?pid=ImgDet&rs=1',
        name: 'William Fichtner',
        role: 'Alexander `Alex` Mahone',
        eps: '59',
    },
    {
        id: 8,
        img: 'https://th.bing.com/th/id/OIP.WiQU_Voqlx2-I8A0UkNS5wHaLJ?pid=ImgDet&rs=1',
        name: 'Paul Adelstein',
        role: 'Paul Kellerman',
        eps: '49',
    },
    {
        id: 9,
        img: 'https://th.bing.com/th/id/OIP.-ZozchNACAjleK0_qTxr9QAAAA?pid=ImgDet&rs=1',
        name: 'Rockmond Dunbar',
        role: 'Benjamin Miles `C-Note` Franklin',
        eps: '43',
    },
    {
        id: 10,
        img: 'https://th.bing.com/th/id/R.1c93096dd795d7c2ea041cce4c6b8d93?rik=xyfPcAIf%2bxtoCA&pid=ImgRaw&r=0',
        name: 'Jodi Lyn O`Keefe',
        role: 'Gretchen Morgan',
        eps: '34',
    },
    {
        id: 11,
        img: 'https://th.bing.com/th/id/OIP.FYgFu-Ht8ePWNUdh1raNFwAAAA?pid=ImgDet&rs=1',
        name: 'Leon Russom',
        role: 'General Jonathan Krantz',
        eps: '30',
    },
    {
        id: 12,
        img: 'https://th.bing.com/th/id/OIP.XA4Eeir0fFU2BUYtwQlB6wHaJQ?pid=ImgDet&rs=1',
        name: 'Marshall Allman',
        role: 'LJ Burrows',
        eps: '27',
    },
    {
        id: 13,
        img: 'https://th.bing.com/th/id/OIP.tQj6_do8XpzEFj489uW8dAAAAA?pid=ImgDet&rs=1',
        name: 'Robin Tunney',
        role: 'Veronica Donovan',
        eps: '23',
    },
    {
        id: 14,
        img: 'https://th.bing.com/th/id/R.07d2d390df2f513b1ad3d907f8ab000e?rik=xWj25CkqSw%2b%2bpA&pid=ImgRaw&r=0',
        name: 'Stacy Keach',
        role: 'Warden Henry Pope',
        eps: '24',
    },
    {
        id: 15,
        img: 'https://th.bing.com/th/id/R.44e4277c786a02772d491e32fccbafbe?rik=V2UcApb%2b5jGFOA&pid=ImgRaw&r=0',
        name: 'Michael Rapaport',
        role: 'Don Self',
        eps: '22',
    },
    {
        id: 16,
        img: 'https://th.bing.com/th/id/R.2f3713c7f0265d668b56761b001823cd?rik=Alv8RqUF5RPaFA&pid=ImgRaw&r=0',
        name: 'Peter Stormare',
        role: 'John Abruzzi',
        eps: '25',
    },
    {
        id: 17,
        img: 'https://th.bing.com/th/id/OIP.BU5R2DPuW90mf_QiiIWxoAAAAA?pid=ImgDet&rs=1',
        name: 'Phillip Edward Van Lear',
        role: 'Louis Patterson',
        eps: '21',
    },
    {
        id: 18,
        img: 'https://th.bing.com/th/id/R.e79f55133f94a513553e0c5358eb8de4?rik=5RBHoCCo8COnpA&pid=ImgRaw&r=0',
        name: 'Muse Watson',
        role: 'Charles Westmoreland',
        eps: '20',
    },
]